### ISSUE TITLE
Issues with current version of MMS Module on iViewer Next v4.0.210 build 210

### ISSUE THREAD

**Issue by clearav** [CommandFusion/Autonomic-MMS#1]
• Play/Pause button states wrong way round (should show pause while playing, play while paused)
• Song progress/time bar non-interactive
• Some features freeze if iPad locked while app is open:
        o   Play/Pause button
        o   Now Playing feature
        o   Song time/progress bar
        o   Shuffle/Loop buttons
• Last FM button beside Now Playing not working – “Command not enabled”
• Tunein Radio & Spotify Search functions not working.  Search feedback required.
• No option to view Favourites
• Sources button (top right) inactive

**Comment by CF-Terence** [comment]
Play/Pause button states wrong way round (should show pause while playing, play while paused)
- is fine with this suggestion, will update it in the next release.

Song progress/time bar non-interactive
- even in the Mirage software there's no option to seek playing time, just displaying the progress of playback. Still looking into it if there's any possibilities to do seeking.

Some features freeze if iPad locked while app is open: Play/Pause button, Now Playing feature, Song time/progress bar, Shuffle/Loop buttons
- so far I can't replicate the issue over here and mine is running fine. Will continue to do some test.

Last FM button beside Now Playing not working – “Command not enabled”
- that's not the last FM button but is the Scrobbling button. Only works if you have it enabled.

Tunein Radio & Spotify Search functions not working. Search feedback required.
- Can give more info on this? As for mine, the searches are working fine.

No option to view Favourites
- In the todo list.

Sources button (top right) inactive
- Currently is disabled. In the todo list.

Can you let me know what is your setup? Thanks.
