### ISSUE TITLE
clearall throws an exception

### ISSUE THREAD

**Issue by chapcory** [CommandFusion/Autonomic-MMS#10]
i have tried to use clearall function - I get an exception as below

07:45:04> CrestronMobile matched feedback Feedback
07:45:06> SCRIPT: Page changed from 0SourceSelect to 0MMS_Innea with orientation Landscape
07:45:06> SCRIPT: Autonomic MMS-5 Listening
07:45:06> SCRIPT: Exception caught when executing callback function (from, to, orientation) {

```
    CF.log("Page changed from " + from + " to " + to + " with orientation " + orientation);
    if ( to = "0MMS_Innea")
    {
                       CF.watch(CF.FeedbackMatchedEvent, mms.sysName, "Incoming Data", mms.incomingData); 
               CF.log("Autonomic MMS-5 Listening"); 
                               mms.selectZone("Player_B"); 
                                mms.clearall();
                                mms.getStatus();                                                        // Get the starting status of all items.


    }
    else
    if (from= "0MMS_Innea")
    {
                        CF.unwatch(CF.FeedbackMatchedEvent, mms.sysName, "Incoming Data");                                      // Stop watching all incoming data              
                CF.log("Autonomic MMS-5 System Stopped listening"); 

    }
}
```

07:45:06> SCRIPT: TypeError: 'undefined' is not a function (evaluating 'mms.clearall()')
07:45:07> CrestronMobile matched feedback Feedback
07:45:07> d236 = 0
07:45:07> d250 = 1
07:45:07> MMS5 matched feedback Incoming Data
07:45:07> SCRIPT: Exception caught when executing callback undefined
07:45:07> SCRIPT: TypeError: 'undefined' is not an object (evaluating 'a.apply')
07:45:07> CrestronMobile matched feedback Feedback
07:45:07> CrestronMobile matched feedback Feedback
07:45:07> CrestronMobile matched feedback Feedback
07:45:07> s4581 = Player B
07:45:07> a4501 = 0
07:45:07> s4581 = Player B
07:45:07> a4501 = 0
07:45:07> s4581 = Player B
07:45:07> a4501 = 0
07:45:07> s4581 = Player B
07:45:07> a4501 = 0
07:45:07> s4581 = Player B
07:45:07> a4501 = 0
07:45:08> CrestronMobile matched feedback Feedback
07:45:08> CrestronMobile matched feedback Feedback
07:45:09> CrestronMobile matched feedback Feedback
07:45:09> CrestronMobile matched feedback Feedback
07:45:09> CrestronMobile matched feedback Feedback
07:45:09> s46 = 7:45 AM
07:45:09> s45 = Tuesday October 23, 2012
07:45:09> s46 = 7:45 AM
07:45:10> CrestronMobile matched feedback Feedback
07:45:12> CrestronMobile matched feedback Feedback
07:45:12> CrestronMobile matched feedback Feedback
07:45:12> CrestronMobile matched feedback Feedback
07:45:13> CrestronMobile matched feedback Feedback
07:45:14> CrestronMobile matched feedback Feedback
07:45:14> CrestronMobile matched feedback Feedback
07:45:14> CrestronMobile matched feedback Feedback
07:45:15> CrestronMobile matched feedback Feedback
07:45:16> CrestronMobile matched feedback Feedback
07:45:17> CrestronMobile matched feedback Feedback
07:45:17> CrestronMobile matched feedback Feedback
07:45:18> CrestronMobile matched feedback Feedback
07:45:18> CrestronMobile matched feedback Feedback
07:45:19> CrestronMobile matched feedback Feedback
07:45:19> CrestronMobile matched feedback Feedback
07:45:19> s45 = Tuesday October 23, 2012
07:45:19> s46 = 7:45 AM
07:45:20> CrestronMobile matched feedback Feedback
07:45:21> CrestronMobile matched feedback Feedback
07:45:22> CrestronMobile matched feedback Feedback
07:45:22> CrestronMobile matched feedback Feedback
07:45:22> s327 = 69
07:45:22> CrestronMobile matched feedback Feedback
07:45:23> CrestronMobile matched feedback Feedback
07:45:24> CrestronMobile matched feedback Feedback
07:45:26> CrestronMobile matched feedback Feedback
07:45:28> CrestronMobile matched feedback Feedback
07:45:29> CrestronMobile matched feedback Feedback
07:45:29> CrestronMobile matched feedback Feedback
07:45:29> s45 = Tuesday October 23, 2012
07:45:29> s46 = 7:45 AM
07:45:30> CrestronMobile matched feedback Feedback
07:45:32> CrestronMobile matched feedback Feedback
07:45:34> CrestronMobile matched feedback Feedback
07:45:35> CrestronMobile matched feedback Feedback
07:45:35> CrestronMobile matched feedback Feedback
07:45:36> CrestronMobile matched feedback Feedback
07:45:36> CrestronMobile matched feedback Feedback
07:45:38> CrestronMobile matched feedback Feedback
07:45:39> CrestronMobile matched feedback Feedback
07:45:39> CrestronMobile matched feedback Feedback
07:45:39> s45 = Tuesday October 23, 2012
07:45:39> s46 = 7:45 AM
07:45:39> CrestronMobile matched feedback Feedback
07:45:39> CrestronMobile matched feedback Feedback
07:45:40> CrestronMobile matched feedback Feedback
07:45:40> CrestronMobile matched feedback Feedback
07:45:41> CrestronMobile matched feedback Feedback
07:45:42> CrestronMobile matched feedback Feedback
07:45:42> CrestronMobile matched feedback Feedback
07:45:42> s327 = 70
07:45:42> CrestronMobile matched feedback Feedback
07:45:43> CrestronMobile matched feedback Feedback
07:45:44> CrestronMobile matched feedback Feedback
07:45:45> CrestronMobile matched feedback Feedback
07:45:45> CrestronMobile matched feedback Feedback
07:45:46> CrestronMobile matched feedback Feedback
07:45:46> CrestronMobile matched feedback Feedback
07:45:47> CrestronMobile matched feedback Feedback
07:45:47> CrestronMobile matched feedback Feedback
07:45:48> CrestronMobile matched feedback Feedback
07:45:48> CrestronMobile matched feedback Feedback
07:45:49> CrestronMobile matched feedback Feedback
07:45:49> CrestronMobile matched feedback Feedback
07:45:49> s45 = Tuesday October 23, 2012
07:45:49> s46 = 7:45 AM
07:45:50> CrestronMobile matched feedback Feedback
07:45:51> CrestronMobile matched feedback Feedback
07:45:52> CrestronMobile matched feedback Feedback
07:45:52> CrestronMobile matched feedback Feedback
07:45:52> CrestronMobile matched feedback Feedback
07:45:53> CrestronMobile matched feedback Feedback
07:45:55> CrestronMobile matched feedback Feedback
07:45:56> CrestronMobile matched feedback Feedback
07:45:57> CrestronMobile matched feedback Feedback
07:45:57> CrestronMobile matched feedback Feedback
07:45:57> s327 = 69
07:45:58> CrestronMobile matched feedback Feedback
07:45:58> CrestronMobile matched feedback Feedback
07:45:59> CrestronMobile matched feedback Feedback
07:45:59> CrestronMobile matched feedback Feedback
07:45:59> s45 = Tuesday October 23, 2012
07:45:59> s46 = 7:45 AM
07:46:00> CrestronMobile matched feedback Feedback
07:46:03> CrestronMobile matched feedback Feedback
07:46:04> CrestronMobile matched feedback Feedback
07:46:06> CrestronMobile matched feedback Feedback
07:46:06> CrestronMobile matched feedback Feedback
07:46:06> CrestronMobile matched feedback Feedback
07:46:07> CrestronMobile matched feedback Feedback
07:46:08> CrestronMobile matched feedback Feedback
07:46:09> CrestronMobile matched feedback Feedback
07:46:09> CrestronMobile matched feedback Feedback
07:46:09> CrestronMobile matched feedback Feedback
07:46:09> s46 = 7:46 AM
07:46:09> s45 = Tuesday October 23, 2012
07:46:09> s46 = 7:46 AM
07:46:10> CrestronMobile matched feedback Feedback
07:46:12> CrestronMobile matched feedback Feedback
07:46:14> CrestronMobile matched feedback Feedback
07:46:16> CrestronMobile matched feedback Feedback
07:46:17> CrestronMobile matched feedback Feedback
07:46:17> CrestronMobile matched feedback Feedback
07:46:17> s327 = 70
07:46:18> CrestronMobile matched feedback Feedback
07:46:18> CrestronMobile matched feedback Feedback
07:46:19> CrestronMobile matched feedback Feedback
07:46:19> CrestronMobile matched feedback Feedback
07:46:19> s45 = Tuesday October 23, 2012
07:46:19> s46 = 7:46 AM
07:46:19> CrestronMobile matched feedback Feedback
07:46:19> CrestronMobile matched feedback Feedback
07:46:20> CrestronMobile matched feedback Feedback
07:46:20> CrestronMobile matched feedback Feedback
07:46:22> CrestronMobile matched feedback Feedback
07:46:22> CrestronMobile matched feedback Feedback
07:46:22> s327 = 69
07:46:22> CrestronMobile matched feedback Feedback
07:46:23> CrestronMobile matched feedback Feedback
07:46:25> CrestronMobile matched feedback Feedback
07:46:25> CrestronMobile matched feedback Feedback
07:46:25> CrestronMobile matched feedback Feedback
07:46:26> CrestronMobile matched feedback Feedback
07:46:26> CrestronMobile matched feedback Feedback
07:46:28> CrestronMobile matched feedback Feedback
07:46:29> CrestronMobile matched feedback Feedback
07:46:29> CrestronMobile matched feedback Feedback
07:46:29> s45 = Tuesday October 23, 2012
07:46:29> s46 = 7:46 AM
07:46:30> CrestronMobile matched feedback Feedback
07:46:32> CrestronMobile matched feedback Feedback

**Comment by CF-Terence** [comment]
I can't find a mms.clearall(); in my JS code. Can you make sure that this function is available in your code and post the snippet of it?

**Comment by chapcory** [comment]
Please note, the exception i was getting was cleared up by pulling the space from "incoming data"  in system manager and js.
This was suggested by  Jordan in Oct 23 posting under topic "on or off a page "  (which i started).

The exception was random, it occurred other times besides clearAll.

Chap

starts on line 1844.

```
clearAll: function() {

    // clear all lists of previous entries
    CF.listRemove(mms.lstAlbum);                
    CF.listRemove(mms.lstArtist);               
    CF.listRemove(mms.lstGenre);                
    CF.listRemove(mms.lstPlaylist);         
    CF.listRemove(mms.lstRadioSource);
    CF.listRemove(mms.lstRadioStation);     
    CF.listRemove(mms.lstPickListItem);
    CF.listRemove(mms.lstQueue);

    // clear all arrays of previous entries
    mms.arrayAlbum = [];                    // Album
    mms.arrayArtist = [];                   // Artist
    mms.arrayGenre = [];                    // Genre
    mms.arrayPlaylist = [];             // Playlist
    mms.arrayRadioSource = [];              // Radio Sources
    mms.arrayRadioStation = [],         // Radio Stations
    mms.arrayPickListItem = [];         // PickListItem
    mms.arrayQueue = [];                    // Now Playing
    mms.artistLetters = [];             // Artist letters

    // clear the irrelevant text fields and slider values
    CF.setJoins([                                                                       
            {join: "s4601", value: ""},
            {join: mms.txtPlayStatus, value: ""},
            {join: mms.txtTrackStatus, value: ""},              
            {join: mms.txtCoverArt, value: ""},         
            {join: mms.txtTrackTitle, value: ""},           
            {join: mms.txtAlbum, value: ""},
            {join: mms.txtArtist, value: ""},           
            {join: mms.txtTrackTime, value: ""},
            {join: mms.txtTrackDuration, value: ""},
            {join: mms.srchAlbum, value: ""},           
            {join: mms.srchArtist, value: ""},
            {join: mms.srchGenre, value: ""},           
            {join: mms.srchPlaylist, value: ""},
            {join: mms.srchRadioSource, value: ""},         
            {join: mms.srchQueue, value: ""},
            {join: mms.txtPlaylist, value: ""},
            {join: mms.txtVolumeLevel, value: ""},
            {join: mms.sldVolumeControl, value: 0},     // volume slider
            {join: mms.sldTrackTime, value: 0},         // track time feedback slider
    ]);
},
```

**Comment by CF-Terence** [comment]
Based on the error log, it shows that mms.clearall() is undefined = is not available or does not exist. The error would come from the caps in the A in the clearAll() function instead of clearall(). 

So you should be calling mms.clearAll() instead.
