### ISSUE TITLE
four across images

### ISSUE THREAD

**Issue by chapcory** [CommandFusion/Autonomic-MMS#11]
This isn't an issue, i'm just trying to fill in a 4 across, list. For this gui.

I cannot build the subpage correctly.  I've tried using a scheme from the Jriver, but the dat is organized differently.

Maybe you have some example code.
The issue is that not all the data is available  (except in the array,and I dont know how to extract that)

TIA,
Chap

**Comment by CF-Terence** [comment]
Hi you can have a look at the XBMC module https://github.com/CommandFusion/XBMC and look at the section of the script for building a movie wall (self.buildMovieWall function) in the xbmcapp.js file.

The example is for a 3 across x N rows list but you can easily modify it for a 4 x N.

**Comment by moseylevy** [comment]
did you ever get this working for the MMS?

**Comment by chapcory** [comment]
yeah, about 5 hours ago.
now to he tweaks...
thanks for asking.  if you want some code, as soon as its stable, ill
pass along.
c
Chap Cory
Systems Architect
Martha's Vineyard Audio Video - _Electronic Systems Contractor_
508-687-0500
787.463.5793
chap@mvaudiovideo.com
www.mvaudiovideo.com

**Comment by moseylevy** [comment]
awesome. i would love it!
shoot my an email 
ml at bsav.tv

id be happy to return the favor in the future.
