### ISSUE TITLE
v4.0.214 build 215 Cannot see lists and buttons don't function

### ISSUE THREAD

**Issue by DR7** [CommandFusion/Autonomic-MMS#15]
After loading the files and changing IP's as mentioned in read me I can only see cover art and the artist, album,track and analog bar for track time.

Transports and volume works but I cannot see lists of anything when pressing any buttons above the cover art such as Albums, Artists etc. 

Settings, Actions and Zone an sources also seem to do nothing for me? Show feedback when pressed and thats it

**Comment by CF-Terence** [comment]
Can you list down the setup of your system - ipad generation, IOS version, iViewer version, MMS model, etc. for easier troubleshooting? Thanks!

**Comment by DR7** [comment]
iPad model = MD510C - 4th gen Retina

IOS=6.0.1

iViewer = v4.0.214 build 215

MMS = MMS-5A

Note that I also have the Autonomic MMS v3.1 module loaded on my Crestron AV2 and the client is using port 5004 and I have been testing the MMS with an XPnale in my Crestron system and it works fine...just thought to mention if having this module using port 5004 could cause any sort of conflict.

I uploaded the file using the upload service in guiDesigner and though perhaps that was the problems so I placed the "GUI" directory online and point to the "File URL" and everything loads fine and it tells me at the top left "Server connected" but as mentioned in the first post I have limited functionality and no lists show in the center at all.

Thanks for any assistance at all and thank you for making this code and interface public for us Autonomic an CF users.

**Comment by CF-Terence** [comment]
Can you try to disable the Crestron control and just use the CF module directly to control? This might eliminate the possibility of port conflicts used by the different modules. Unfortunately we don't have a MMS-5A unit to duplicate the problem - this module was tested only on a MMS5 but looking at the protocol documents, there are no changes and differences mentioned in both models so this shouldn't be an issue. 

Can you also try to download the latest version of the iViewer Next and try it out?

**Comment by DR7** [comment]
I disabled the module in my program and stil have the same problem. I'm not
sure what really is going on and I basically followed these directions
below and loaded the file. Until I figure it out I still have the module
but really liked the layout you created.

Thanks

### Guidelines for module usage:

Enter the IP address/hostname of the MMS server in the System Manager
properties and Global Token properties (Edit > Project Properties > Global
Token Manager) and load the GUI file.

**Comment by CF-Terence** [comment]
Tried with iViewer Next?

Pretty strange response with Settings, Actions and Zone buttons as their basically toggle buttons and the corresponding drop down menus should show/hide as the button is being toggled - there's no feedback or any commands being involved.

Sources is not enabled at the moment.

Can you remove your license from your project and reinsert it again and try and see?

Else, you can send me a stripped down version of your GUI file for me to have a look at terence@commandfusion.com

**Comment by DR7** [comment]
I have it working now, sadly it was my key...I have not use CF for quite some time and just changed to my new iPad and was not aware the key was not installed properly as I uploaded some other small things and they worked. Glad to see it working, excellent coding job and graphics...thank you!!

**Comment by CF-Terence** [comment]
No worries ... glad to hear that it's working now. Cheers!
