### ISSUE TITLE
List population - iViewer v4.0.214 build 215 / iOS 5.1.1

### ISSUE THREAD

**Issue by AnthonyBatchelor** [CommandFusion/Autonomic-MMS#2]
Hi Terrance,

I have been playing about with this MMS module for a week or two, but it seems I can only ever get 10 items to appear in the dynamic list for Radio Sources when using TuneIn Radio. Is this limited?!

**Comment by CF-Terence** [comment]
Hi, I'm running the same iViewer version and IOS too but don't have the same issue - my Local Radio Sources' list from TuneInradio has more than 180 stations.  How about lists for other Radio Stations i.e. Pandora, Rhapsody, Spotify, etc. ?

You can double check by using the Autonomic's Mirage software - compare both list of Radio Stations, mine has exactly the same content for both lists.

**Comment by AnthonyBatchelor** [comment]
Ok just had a check with the MMS web interface, definitely getting more in the list there. My MMS-2 is currently running firmware version 3.0.11466.0 Release if that makes any difference, which is the most recent.

Currently I do not have it set with a Spotify account or similar. I also see the same issue as in the previous issue post on this thread, where the 'NowPlaying' items do not seem to update correctly if the iPad goes to sleep and then woken up again.

Excellent functionality otherwise!

**Comment by AnthonyBatchelor** [comment]
It seems if you put the system URL and Name into the JavaScript module and not in Global Tokens, it causes this problem! I assumed it would be interchangeable?

...Update to this, in actual fact it has not cured the problem. It was the re-load of the GUI that caused the list to load correctly the first time round, but there after it will only load 10 items.

**Comment by CF-Terence** [comment]
The JS values are for additional backup purpose if the Global Tokens values are not able to be read at startup e.g. if someone accidentally deletes the values in the tokens. Both of them should have the same value - in the case where both are available, the Global Tokens values are taken as the main.

Back to the lists, you don't see any problems in other lists i.e. Albums, Artists, Playlists, etc. only InTune Radio? What are the settings of your iViewer 4? By the way, are you using the new iPad? I'm using ipad1 here.

On another note, have managed to reproduce the "Now Playing" issue recently and am looking into it.

**Comment by AnthonyBatchelor** [comment]
I think some of my issues are related to the fact I have integrated the MMS module into my main project that is running CrestronMobile v3. I have spoken to Florent and I am just making an addition to the CM module to make sure that it excludes the Join range that MMS is using from it's updates. This was clearing all of the information on wake. I am not sure however if this would affect list objects as well?!

Also, now it is in a project with other JavaScript modules, should it make a difference that the system commands for MMS are still calling 'self.[command]' or might this need to be changed?

**Comment by CF-Terence** [comment]
I've updated the module recently to update the list objects and the corresponding joins into the Autonomic module join range (join numbers 4500 - 4605) and the self object changed to mms object.

So, make sure that all other joins for the other modules are not within this range and all calls for Autonomic module should be mms.[command].

**Comment by AnthonyBatchelor** [comment]
Wish I hadn't gone off and changed the layout to my own skin now, also I made a portrait version of all the subpages, so had to go through everything and add the 'mms.[function]' to it. Anyway that is all done now and working with the updated JS file. Lists still not populating fully yet, but making progress!

I have also managed to get a Spotify Premium account to test with, but so far on the iPad I cannot get passed Radio Sources > Spotify > New search... then nothing where i might expect the iPad keyboard to popup for entry. Seems to do the same for TuneIn Radio > New search. **Updated - Problem Found**

Thanks for your help so far! :-)

**Comment by AnthonyBatchelor** [comment]
Ok still working on the list propagation, trying to find out what the contents of mms.arrayRadioSource when the iPad is woken up. At the moment, after first load I hit Radio Sources and I get options in the list for Spotify and TuneIn Radio. After it is woken out of sleep, choosing the same option Spotify disappears and I only see TuneIn Radio.

I have spoken to Jarrod about debugging, it seems you cannot continue to debug the JavaScript via Safari > Bonjour as it shuts down the connection. I was just interested to see if it is the Autonomics not reporting the list correctly, and then examine the contents of the array where we would expect this information to be.

Also my apologies, I forgot to mention I am using an iPad 2 and iViewer settings are:
Enable Multitasking = On
Disconnect On Exit / Sleep = On (Recommended by Florent for best practice with CrestronMobile v3)

**Comment by CF-Terence** [comment]
Try with multitasking and disconnect both on OFF mode and let me know your results.Also if you want, you can send me a stripped-down version of your GUI file for me to have a look.

I'll try with both the multitasking and disconnect on exit/sleep on and see if I can reproduce the same issue. 

You can actually track the activity of your web interface (either from using the iViewer module or the Mirage software) opening a telnet connection on port 5004, send a "subscribelog" command, and watching how the web interface handles it.

You can also try to increase the number of items that you taking back from the list by sending the command "BrowseRadioStations 1 100" instead of "BrowseRadioStations" only. You can read more about it in pg.11 of the pdf IP Control Protocol document.

**Comment by AnthonyBatchelor** [comment]
Yes setting Multitasking to 'OFF' does indeed fix the problem because it is reloading the app from fresh. Unfortunately this has adverse affects on the CrestronMobile connection and causes the iPad to be far less responsive on start than we would like.

With Multitasking switched 'ON' the app coming out of sleep wakes up much faster, which we would like to be able to maintain for our users.

**Comment by AnthonyBatchelor** [comment]
Here are the results from the Telnet session before sleep and after wake (Multitasking = ON):

BEFORE------
2012-09-05 15:34:52,824 [26] DEBUG - user@192.168.10.87:54200<--BrowseRadioSources
2012-09-05 15:34:52,842 [39] DEBUG - user@127.0.0.1:49179-->StateChanged Main TrackTime=127
2012-09-05 15:34:52,843 [39] DEBUG - user@192.168.10.82:49991-->StateChanged Main TrackTime=127
2012-09-05 15:34:52,843 [39] DEBUG - user@192.168.10.87:54200-->StateChanged Main TrackTime=127
2012-09-05 15:34:53,031 [26] DEBUG - user@192.168.10.87:54200-->BeginRadioSources Total=2 Start=1 Alpha=0 Caption="Radio sources"
  RadioSource {fbbcedb1-af64-4c3f-bfe5-000000000100} "Spotify"
  RadioSource {fbbcedb1-af64-4c3f-bfe5-000000000020} "TuneIn Radio"
EndRadioSources NoMore

AFTER-------
2012-09-05 15:35:09,692 [39] DEBUG - user@192.168.10.87:54208-->BeginRadioSources Total=1 Start=1 Alpha=0 Caption="Radio sources"
  RadioSource {fbbcedb1-af64-4c3f-bfe5-000000000020} "TuneIn Radio"
EndRadioSources NoMore

So for some reason the sleeping of the iPad causes the Autonomics Server to report back incorrectly after it has been woken up. Could this be down to how the module is managing the connection?! The main difference is that coming out of sleep mode I can see the Autonomics simply reconnects to user@[my iPad IP]. Where as on the first time it loads up it does the same, but also a 'GetStatus' request is sent.

I have the full log of this if that is helpful, not sure where to upload that mind you!

**Comment by AnthonyBatchelor** [comment]
Ok I think I have solved the problem. When the iPad reconnects to MMS after sleep, the MMS gives the iPad connection a new ID number for sending information to. So the following update to the JavaScript module is needed:

```
onGUIResumed: function() {
    mms.setEncoding();
    mms.setCurrentInstance();
    mms.setPickListCount(1000);
    mms.subcribeEventOn();
    mms.getStatus();
},
```

This gives the newly connected instance all the correct properties and now the list propagates correctly!

**Comment by CF-Terence** [comment]
Great work in troubleshooting and debugging there. And also thanks for the fix. Will incorporate this into the next update revision.
