### ISSUE TITLE
Artwork Refresh - Spotify

### ISSUE THREAD

**Issue by AnthonyBatchelor** [CommandFusion/Autonomic-MMS#4]
Hi Terrance, I have managed to troubleshoot another issue today. You may be aware of it already, but I thought I would share my solution.

When using Spotify, the Artwork does not update as you skip through tracks. The reason being is that Spotify takes only one GUID for all of its operations. Hence as a track changes, it does not re-issue the GUID.

There is however a parameter that it does update called 'MediaArtChanged=' which I can see you have already put in the Regex table. I have created the following code to utilise this feedback and update the artwork:

Firstly a variable to hold the current URL (in this case containing the GUID for Spotify) under 'Global variables' -

```
currentArtworkURL: "",  // Container for the current artwork URL.
```

Then an additional line in the 'mms.stateThumbnailRegex' test case -

```
            currentArtworkURL = mms.coverart+matches[1]+"&e404=1"; 
```

And finally a new test case for 'mms.stateMediaArtChangedRegex' -

```
    else if (mms.stateMediaArtChangedRegex.test(matchedString)) {

            CF.setJoin(mms.txtCoverArt, "");
            CF.setJoin(mms.txtCoverArt, currentArtworkURL);
    }
```

This clears the URL on the serial join and then reloads it.

Hope this helps, if you have not already found this solution!

**Comment by CF-Terence** [comment]
Thanks for the troubleshooting - will include this in the next update of the module.
