### ISSUE TITLE
Search Input - Spotify

### ISSUE THREAD

**Issue by AnthonyBatchelor** [CommandFusion/Autonomic-MMS#5]
Some testing with the search feature in Spotify has pulled up this error:

15:49:56> SCRIPT: SearchString=AckButton 78415983-57f0-4889-8620-c4a4025c3fd3 OK Sub focus
15:49:56> s4519 = Sub focus
15:49:56> MMS-2 matched feedback Incoming Data
15:49:56> s1 = Error: Invalid argument count. 'AckButton' takes 3 arguments.

I have printed out using CF.log the contents of the string being sent for the search, I have labelled it 'SearchString=' here.

I can't seem to work out from the IP protocol document what the construction of the string to return should be, but clearly it is expecting something slightly different. Is this the lastest IP protocol doc. for MMS?

**Comment by AnthonyBatchelor** [comment]
Fixed this one now by watching the web interface, the JavaScript misses out the double quotes around srchstring:

submitSearch:               function(guid, srchstring) { mms.sendCmd(guid + "OK \"" + srchstring + "\""); },

**Comment by CF-Terence** [comment]
Thanks for the feedback and solution.
