### ISSUE TITLE
cip errors

### ISSUE THREAD

**Issue by chapcory** [CommandFusion/Autonomic-MMS#9]
I am getting thousands of these errors on my Crestron MC3 coming from ipads running CM V3 and MMS5.
If MMS5 is removed, they stop.

Is it because the join numbers in the 4k range are getting exposed to the CM interface?
I get both serial and digital messages

 CIPCommandProcessor.exe # 14:09:58 10-19-2012  #  ProcessIncomingSerialJoinFromClient - NO Data element found. Nothing to send to logic.

Thanks, 
Chap

PS:
I have added a "now playing " popup which responds to the regex that says to jump.

I can send you the code if you wish.
Also, I have tried your suggestion to stop the incoming watching, but on reentry I get two copies of everything.  (Means there are two watchers).   Gotta study more.

**Comment by CF-Terence** [comment]
All CIP joins should be 4000 and below - that's why the module joins are 4000 and above. Do send me your code to have a look - thanks!
